### ISSUE TITLE
help

### ISSUE THREAD

**Issue by jaan143** [KalimAmzad/Scribd-Premium-Book-PDF-Downloader#1]
thank you very much for your script
i am trying to using your script but i am getting this errors kindly help me to solve it

PS C:\Users\Hp\Downloads\Compressed\scribd-downloader-master_2\scribd-downloader-master> scribdl https://www.scribd.com/book/153948215/The-Emotional-Eater-s-Repair-Manual-A-Practical-Mind-Body-Spirit-Guide-for-Putting-an-End-to-Overeating-and-Dieting
Traceback (most recent call last):
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\Scripts\scribdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('scribd-downloader==1.3.1', 'console_scripts', 'scribdl')())
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\Scripts\scribdl-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\importlib\metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\scribd_downloader-1.3.1-py3.9.egg\scribdl\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1414, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1388, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1369, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 423, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 716, in spec_from_file_location
  File "<frozen zipimport>", line 191, in get_filename
  File "<frozen zipimport>", line 713, in _get_module_code
  File "<frozen zipimport>", line 647, in _compile_source
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\site-packages\scribd_downloader-1.3.1-py3.9.egg\scribdl\downloader.py", line 149
    print("Document Downloading") if "document" in self.url
                                                           ^
SyntaxError: invalid syntax
PS C:\Users\Hp\Downloads\Compressed\scribd-downloader-master_2\scribd-downloader-master>

**Comment by KalimAmzad** [comment]
Thanks for raising the issue. 
**Script is updated and also follow the package installation guideline  at readme**
